### ISSUE TITLE
Grouping by project

### ISSUE THREAD

**Issue by jonathanvansina** [kamaln7/do-ansible-inventory#3]
Is it an idea to create a group per project?

**Comment by kamaln7** [comment]
Hi @jonathanvansina, thank you for the suggestion! I really like this idea

**Comment by markverg** [comment]
Would love to see this too!

**Comment by kamaln7** [comment]
Hey @jonathanvansina & @markverg, I just published a new release that adds support for grouping by project. It is enabled by default and can be disabled by passing `--no-group-by-project`.

👉🏼  https://github.com/do-community/do-ansible-inventory/releases/tag/v2.0.0
